### ISSUE TITLE
Error: connect EADDRNOTAVAIL - exception cancels the download

### ISSUE THREAD

**Issue by Zaniyar** [ToTheMax/Snapchat-All-Memories-Downloader#1]
It downloads some but then i get this error: 

```
(base)macbook:mydata_15883 user$ node main.js 
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: connect EADDRNOTAVAIL xxx.xxx.xx.xxx:xxx - Local (0.0.0.0:0)
    at internalConnect (net.js:907:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1050:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: 'xxx.xxx.xx.xx',
  port: 443
```

**Comment by ToTheMax** [comment]
Thanks for mentioning, I'll have a look at catching these errors and retrying the downloads.

**Comment by ToTheMax** [comment]
I fixed it by adding a limitation to the number concurrent connections. You can play around with it by setting the "-c" flag. Let me know if it works!
