### ISSUE TITLE
node main.js internal/modules/cjs/loader.js:883

### ISSUE THREAD

**Issue by NicciZar** [ToTheMax/Snapchat-All-Memories-Downloader#27]
Hello,

I just installed nodejs and tried to run that main.js via cmd. `node main.js`
It threw an error message but I dont know what to do with it..

I also ran `npm install` in a seperate cmd window and it told me everything was up to date.
Im new to node and js

```
node main.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'moment'
Require stack:
- D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\main.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\main.js:6:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'D:\\Downloads\\Internet_Download_Manager_Downloads\\mydata~1608490438992\\main.js'←[39m
  ]
}

```
Thank you :)

**Comment by ToTheMax** [comment]
You need to first run `npm install`, did you do that?

**Comment by NicciZar** [comment]
I just ran that command. I did not know I had to open the cmd in the folder where the files are located.

I just got:
```

npm install

> utimes@4.0.2 install D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\node_modules\utimes
> node-gyp rebuild


D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\node_modules\utimes>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\node_modules\utimes
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN snapchat-all-memories-downloader@1.0.0 No repository field.
npm WARN snapchat-all-memories-downloader@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utimes@4.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utimes@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicci\AppData\Roaming\npm-cache\_logs\2020-12-22T11_30_53_699Z-debug.log

```

I also found another person who made a script (in my case a .exe) for downloading memories.

**Comment by ToTheMax** [comment]
Can you download Python and try again? https://www.python.org/downloads/

**Comment by NicciZar** [comment]
I reinstalled python but I still get that error message..

**Comment by ToTheMax** [comment]
Try this older version: https://github.com/ToTheMax/Snapchat-All-Memories-Downloader/tree/7108846391fb92df919d79789514faedb4461098
It doesn't require any modules

**Comment by NicciZar** [comment]
it went through as far as i can see
```

main.js

D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992>npm install
npm WARN saveError ENOENT: no such file or directory, open 'D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'D:\Downloads\Internet_Download_Manager_Downloads\mydata~1608490438992\package.json'
npm WARN mydata~1608490438992 No description
npm WARN mydata~1608490438992 No repository field.
npm WARN mydata~1608490438992 No README data
npm WARN mydata~1608490438992 No license field.

up to date in 0.541s
found 0 vulnerabilities

```

then only run `main.js` via cmd?

**Comment by NicciZar** [comment]
Do you know if its possible to download the "My Eyes only" section of snapchat with this tool?

**Comment by ToTheMax** [comment]
You dont have to run npm install for the older version indeed. 
Snapchat might've not added that section to the downloads

**Comment by NicciZar** [comment]
Oh okay. Thank you for helping out 👍
