### ISSUE TITLE
Issue when not creating the "Downloads" & "Memories" Folder in the source file directory

### ISSUE THREAD

**Issue by Cloud-Kid** [ToTheMax/Snapchat-All-Memories-Downloader#49]
Hi, 

First, thanks for your project, it helped me after trying maybe 4 or 5 different Python scripts.
I followed the documentation letter by letter but I had an error when trying to download from the JSON file in an other folder and to output the result in yet another directory.

I tried to execute the following :
 `node main.js -c 50 -f "my_memories_json_path.json" -o "Downloads_folder"`

But it didn't work, I had the following error :

`
Error: Cannot find module '././json/memories_history.json'
Require stack:
/Downloads/Snapchat-All-Memories-Downloader-master/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/cloudkid/Downloads/Snapchat-All-Memories-Downloader-master/main.js:29:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/cloudkid/Downloads/Snapchat-All-Memories-Downloader-master/main.js'
  ]
}
`

I then created the "./json" & "./Download" folder, just like in your example at the root of your project directory. I've copied the memories.json in the ./json folder and executed the following :

`node main.js -c 50 -f ./json/memories_history.json -o Downloads`

And it works ! Just wanted to keep you informed, it may also be an error on my side but at least you are informed. Thanks again :1st_place_medal:

**Comment by ToTheMax** [comment]
Thanks for mentioning, I see the error in my code, will prob fix it later today!

**Comment by ToTheMax** [comment]
Just fixed the bug on the filepath parsing, it should work now! (on my machine it does)

**Comment by Cloud-Kid** [comment]
Nice ! Thanks for taking the time to fix it, really appreciate it.
