### ISSUE TITLE
Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by jordanhardee** [ToTheMax/Snapchat-All-Memories-Downloader#64]
When I run node main.js on Trisquel (both with installed node.js and locally run binary):

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jlibre/Documents/snBack2/main.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

**Comment by ToTheMax** [comment]
Did you first run `npm install` ?

**Comment by rageincarnate** [comment]
Hey man @ToTheMax, I was wondering if your team can provide a slightly more detailed tutorial perhaps a video guide for someone completely unfamiliar with coding/JavaScript etc, I am having trouble trying to figure out how this thing works. Hope you can help.

**Comment by ToTheMax** [comment]
Someone already made a video about this, hope it helps: https://www.youtube.com/watch?v=Bt_TuVPOsQ0

**Comment by rageincarnate** [comment]
Dude you're a lifesaver, have a great one.

**Comment by marcinos597** [comment]
Guys nothing was working for me. I made everything like in video. Finally I found a solution. Download Visual Video from here https://visualstudio.microsoft.com/. During installation make sure, that you have selected the "Desktop development with C++" workload. After that reset PC. 
Hope it'll work!

**Comment by AyoCJ** [comment]
@marcinos597 I can't see anything about Visual Video within the installer? Did you mean to type 'Visual Studio' and only select 'Desktop development with C++' as the only thing that needs to be installed?
