### ISSUE TITLE
  'which' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by carlgustafsson01** [ToTheMax/Snapchat-All-Memories-Downloader#94]
After installing the Exiftool and trying to add the -l to the node main.js command I get this:

`      throw new Error('Exiftool not found?', { cause: e })
            ^

Error: Exiftool not found?
    at Exiftool.which (file:///C:/Users/calle/Desktop/Data/Snapchat-All-Memories-Downloader-master/node_modules/@mattduffy/exiftool/src/index.js:361:13) {
  [cause]: Error: Command failed: which exiftool
  'which' is not recognized as an internal or external command,
  operable program or batch file.`

Any ideas?

Also: I've added the Exiftool to the system environment

**Comment by CreeperDoolie** [comment]
I have the same issue:

file:///C:/Users/Colin/Desktop/SnapchatDownloader/node_modules/@mattduffy/exiftool/src/index.js:498
      throw new Error('Exiftool not found?', { cause: e })
            ^

Error: Exiftool not found?
    at Exiftool.which (file:///C:/Users/Colin/Desktop/SnapchatDownloader/node_modules/@mattduffy/exiftool/src/index.js:498:13) {
  [cause]: Error: Command failed: which exiftool
  'which' is not recognized as an internal or external command,
  operable program or batch file.

      at genericNodeError (node:internal/errors:983:15)
      at wrappedFn (node:internal/errors:537:14)
      at ChildProcess.exithandler (node:child_process:414:12)
      at ChildProcess.emit (node:events:524:28)
      at maybeClose (node:internal/child_process:1101:16)
      at Socket.<anonymous> (node:internal/child_process:456:11)
      at Socket.emit (node:events:524:28)
      at Pipe.<anonymous> (node:net:351:12) {
    code: 1,
    killed: false,
    signal: null,
    cmd: 'which exiftool',
    stdout: '',
    stderr: "'which' is not recognized as an internal or external command,\r\n" +
      'operable program or batch file.\r\n'
  }
}

Node.js v22.13.0

Looking at supporting documentation for this tool I only see support for linux and MacOS. I assume you are using Windows as well. Not sure if this is the reason but this is all I can find.

**Comment by ToTheMax** [comment]
As you can see above I made a PR with a potential fix, could you check whether this works on Windows before I merge it? 
Thanks!

**Comment by carlgustafsson01** [comment]
This worked flawlessly for me it appears! I've got everything correctly downloaded but haven't done any bug testing tough. Anything you want me to try?

**Comment by ToTheMax** [comment]
Thanks for your help!
